# Generated by Django 4.2.5 on 2023-10-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_remove_category_name_category_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
